//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string About_Agent { get; set; }
        public string Email { get; set; }
        public decimal CNIC { get; set; }
        public decimal Phone_Number { get; set; }
        public string Picture { get; set; }
        public decimal Office_Number { get; set; }
    }
}
