//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Propert_Id { get; set; }
        public string Feature_Name { get; set; }
        public string Description { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
