//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Property_Id { get; set; }
        public string Property_Type { get; set; }
        public int Property_Adress_Id { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Property_Date { get; set; }
        public Nullable<int> No_Of_Rooms { get; set; }
        public string Area_Size { get; set; }
        public Nullable<int> Price { get; set; }
        public byte[] Property_image { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Room Room { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
