//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Property_Id { get; set; }
        public string Room_Name { get; set; }
        public string Area { get; set; }
        public byte[] Room_Image { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
